# Generated by Django 2.2.17 on 2021-01-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
