# Generated by Django 2.2.17 on 2021-01-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210107_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
