# Generated by Django 2.2.17 on 2021-01-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210107_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.PositiveIntegerField(default=4500104)),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('index', models.PositiveSmallIntegerField()),
                ('postcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Postcard')),
            ],
        ),
    ]
