# Generated by Django 2.2.17 on 2021-01-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210116_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='textcolor',
            field=models.CharField(default='#ff0000', max_length=10),
        ),
    ]
